name: Python CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Debug - List Files
      run: |
        ls -R
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app_python/requirements.txt

    - name: Run Linter (flake8)
      run: |
        pip install flake8
        flake8 app_python/web_app.py app_python/test_web_app.py

    - name: Run Tests
      run: |
        python -m unittest discover app_python
